Repository locationtech/udig-platform, pull requests merged in 2019-09, with the labels that each got.

#356 upgrade to tycho 1.4.0
  pom.xml
Labels: improvement

#293 fix Feature Table view sorting and selection problems
  plugins/org.locationtech.udig.ui.tests/src/org/locationtech/udig/ui/AttributeComparatorTest.java
  plugins/org.locationtech.udig.ui.tests/src/org/locationtech/udig/ui/FIDComparatorTest.java
  plugins/org.locationtech.udig.ui.tests/src/org/locationtech/udig/ui/SelectionComparatorTest.java
  plugins/org.locationtech.udig.ui/src/org/locationtech/udig/ui/AttributeColumnSortListener.java
  plugins/org.locationtech.udig.ui/src/org/locationtech/udig/ui/AttributeComparator.java
  plugins/org.locationtech.udig.ui/src/org/locationtech/udig/ui/FIDComparator.java
  plugins/org.locationtech.udig.ui/src/org/locationtech/udig/ui/FeatureTableContentProvider.java
  plugins/org.locationtech.udig.ui/src/org/locationtech/udig/ui/FeatureTableControl.java
  plugins/org.locationtech.udig.ui/src/org/locationtech/udig/ui/SelectionComparator.java
Labels: bug

#218 Improvements related to bulk feature copy or move between layers
  plugins/org.locationtech.udig.core.tests/fragment.xml
  plugins/org.locationtech.udig.core.tests/src/org/locationtech/udig/core/AdapterUtilTest.java
  plugins/org.locationtech.udig.core.tests/src/org/locationtech/udig/core/DataUtilitiesTest.java
  plugins/org.locationtech.udig.core.tests/src/org/locationtech/udig/core/FeatureUtilsTest.java
  plugins/org.locationtech.udig.core.tests/src/org/locationtech/udig/core/NumberAdaptableFactory.java
  plugins/org.locationtech.udig.core/src/org/locationtech/udig/core/AdapterUtil.java
  plugins/org.locationtech.udig.core/src/org/locationtech/udig/core/internal/FeatureUtils.java
  plugins/org.locationtech.udig.tools.jgrass/src/org/locationtech/udig/tools/jgrass/utils/OperationUtils.java
Labels: improvement

#306 support for text tool contribution and fix of multiple listeners
  plugins/org.locationtech.udig.project.ui/src/org/locationtech/udig/project/ui/tool/options/ToolOptionContributionItem.java
Labels: bug, improvement

#305 Rollback issue
  plugins/org.locationtech.udig.tool.edit.tests/src/org/locationtech/udig/tools/edit/BehaviourCommandTest.java
  plugins/org.locationtech.udig.tool.edit/src/org/locationtech/udig/tools/edit/BehaviourCommand.java
Labels: bug

#292 Disallow DropFilterAction between same layers
  plugins/org.locationtech.udig.project.ui/src/org/locationtech/udig/project/ui/internal/dragdrop/DropFilterAction.java
Labels: improvement
